repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: rustfmt non-vendored files
        entry: scripts/rustfmt-non-vendored --check
        language: system
        pass_filenames: false
        types_or: [rust]
